sky-uk/toolkit-ui

CHANGELOG.md
components/_select.scss
package.json

Fix for IE not animating hover - moved hover states to button rather than use the hidden input. Also added focus style that looks like a button highlight rather than the ticked state to avoid confusion when toggling

fix for IE not animating hover

---

CHANGELOG.md
components/_spinner.scss
package.json

The transition on the `.c-spinner` element targeted all properties. The accessibility 'loading' text has a text-indent of 100% which was being transitioned from 0% to 100% over a second. This meant that the loading text was visible until it had indented outside of the `.c-spinner-overlay` container.
I changed the `.c-spinner` transition to target opacity and visibility as these are the properties that need to be transitioned when the `.is-complete` class is added.

Make transition on c-spinner more specific

---

CHANGELOG.md
components/_select.scss
package.json

As we should still be supporting iOS8, we need to use vendor prefixes for transforms.  There is potentially a bigger job to add these across the whole toolkit, but this fix focuses on getting the select buttons to look and function correctly.

Fix for broken select button display in iOS8

---

CHANGELOG.md
components/_tile.scss
package.json

We have had a few issues with overriding the default hover states for the tiles, currently all content is set to underline which isn't actually correct. Only the title should show underline on hover.
The hover logic has been simplified so specificity is lower too making custom changes easier. One of the main reasons for this is that when using `.c-tile__square`, the `.c-tile__link` losses height and caused some issues, rather than hacking around it this should fix the route of the issue.

Reduced nesting of hoverstates and fixed c-tile__link when square

---

CHANGELOG.md
components/_forms.scss

Fix for tick button appearing on radio button as well as the checkbox component. This will bring the radio buttons inline with the designs.

Removed tick on radio buttons

---

CHANGELOG.md
components/_forms.scss
package.json

Provides keyboard accessibility control on checkbox and radio inputs
`c-form-checkbox__input` now utilises `@include hide-visually();`, complimenting `c-form-checkbox__caption` to replace `c-form-checkbox__faux` for generating the indicator.
New checkbox markup:
```html
<li className="c-form-list__item">
<label for="f-terms_1" className="c-form-checkbox">
<input type="checkbox" className="c-form-checkbox__input" name="f-terms" id="f-terms_1" value="1" />
<span className="c-form-checkbox__caption">I agree to the terms &amp; conditions</span>
</label>
</li>
```
New radio markup:
```html
<li className="c-form-list__item">
<span className="c-form-pair__label">
<label className="c-form-label  u-margin-right">
Which side?
</label>
</span>
<span className="c-form-pair__input">
<label …
```

Fix: Checkbox keyboard control

---

CHANGELOG.md
components/_tile.scss
package.json

When `.c-tile--square.c-tile--collapsable` is applied it causes issues with content on smaller devices.
Expected:
Actual:
Not raised yet
This change will fix the bug by setting the `.c-tile__link` to static positioning so that it correctly adapts height to the content
Browser tested on local dev environment.
Create a tile with `.c-tile.c-tile--square.c-tile--collapsable` and a nested `.c-tile__link`.
See above.

Fix for c-tile link when c-tile--collapsable modifier applied

---

CHANGELOG.md
components/_forms.scss
package.json

Enables checkboxes and radio inputs to be used with multi-line captions.
https://github.com/sky-uk/toolkit-ui/issues/138
cc @aaronthomas 
Beforehand, labels crept below the indicator. There wasn't a consistent margin.
Visual and manual use checks in:
Before:
After:
*Note: Content change in caption not included*

Bug Fix / Checkbox

---

components/_buttons.scss

Borders on buttons are currently fixed to 1px, when scaled to larger sizes this doesn't look correct. This introduces an em based border width so that it scales with font-size.
#90 
Makes buttons handle scaling better
Tested locally on multiple browsers.

Added relative value for button borders

---

CHANGELOG.md
components/_tile.scss

**Dependant on https://github.com/sky-uk/toolkit-core/pull/115**
Full Tile styles.
`.c-tile--full` for tiles that use images without a split. These tiles are white and use a new gradient on hover. `.has-focus` state for keyboard navigation.
https://github.com/sky-uk/toolkit-ui/issues/128
Cleaner design and accessibility improvements using `.has-focus`.
Tests pass on `npm run test`.
Visually checked in all browsers.
Achieves the following styles:

Feature / Full Tile

---

components/_buttons.scss

Unfortunately having some difficulties with this in safari, the bug wasn't spotted originally due to some cached dependencies locally when testing.
#152
Resets the borders to static 1px borders to fix issue in safari where the relative value rounds down rather than 1px. The only way around this would be to include a more complex calc function to ensure value never drops below 1px. This would be pretty overkill, more likely a modifier per use case, I can't see this being heavily used.
Local quick check in main affected browsers.

Revert changes to allow relative borders on buttons

---

CHANGELOG.md
components/_buttons.scss
components/_select.scss

New styles that implement `:focus` to improve accessibility
Extra "box-shadow glow" for buttons and select when in `:focus`.
https://github.com/sky-uk/toolkit-ui/issues/41
https://github.com/sky-uk/toolkit-ui/issues/145
Significantly improves accessibility and keyboard UX.
Visual and manual use checks in:

Focus styles for Buttons and Select

---

CHANGELOG.md
components/_panel.scss

Sets shadow on the top and bottom of panel, rather than all sides.
https://github.com/sky-uk/toolkit-ui/issues/155
cc @aaronthomas 
Corrected to follow brand guidelines
Visual and manual use checks in:

Shadow fix for Panels

---

CHANGELOG.md
components/_tile.scss

At certain resolutions the `.c-tile__media` 55% height was being rounded down causing a gap to appear between it and the caption below, adjusting this to 55.5% ensures this doesn't happen:
*Before:*
*After:*
Please link to the issue here:
Fixes visual bug seen across all tiles.
Tested on local browsers
See description

Added fix for tile media height rounding down

---

CHANGELOG.md
components/_accordion.scss

Added fix for icon vertical alignment
#148
Display issue on IE9
Browser tested on IE9, Chrome and Safari etc via `blackjack-accordion`
Before:
After:

Added fix for accordion icon alignment in IE9

---

CHANGELOG.md
components/_forms.scss

Fixed issue with spacing of text within toolkit select in Chrome.
#157
This fixes an issue with select contents having no bottom spacing and on occasion being cropped.
**Before:**
**After:**
Tested locally across major browsers.

Added fix for positioning of select text content

---

CHANGELOG.md
components/_dropdown.scss

Removes checkbox hack from `c-dropdown` to a state class approach.
https://github.com/sky-uk/toolkit-ui/issues/149
It's a hack - not semantic. Using a stateful approach also allows us to make some accessibility improvements.
Note: Could be used with button or anchor.
This will need to be updated on the Style Guide (something we need to organise going forwards)
```
<div class="c-dropdown">
<button id="dropdown1"
class="c-dropdown__toggle"
aria-haspopup="true"
aria-expanded="false">
Dropdown Menu
</button>
<ul class="c-dropdown__list"
aria-labelledby="dropdown1">
<li class="c-dropdown__item">
<a href="#" class="c-dropdown__link">Menu item 1</a>
</li>
<li class="c-dropdown__item">
<a href="#" class="c-dropdown__link">Menu item 2</a>
</li>
<li class="c-dropdown__item">
<a href="#" …
```

Dropdown Menu Refactor

---

CHANGELOG.md
components/_tile.scss

Currently `.c-tile--square` height is calculated with 100% tile width along with the 5px default padding-bottom causing non square tiles.
Tested locally
**Before:**
**After:**

Fix for height of square tiles being 5px greater than width

---

CHANGELOG.md
components/_accordion.scss
components/_buttons.scss
components/_dropdown.scss
components/_forms.scss
components/_keyline.scss
components/_panel.scss
components/_spinner.scss
components/_tables.scss
components/_tile.scss

Relies on https://github.com/sky-uk/toolkit-core/pull/125
Implementation of new proposed color naming in `toolkit-core`.
https://github.com/sky-uk/toolkit-core/issues/100
Current system for "grey" colours wasn't flexible, any references to these colours needed to be updated to reflect `toolkit-core`.
md5 comparison of outputted css before/after showed no change.
(without changing HEX values)

Colors Refactor

---

CHANGELOG.md
components/_panel.scss

Panels now default to no max-height, with `c-panel--full` to achieve the previous `100vh` effect.
https://github.com/sky-uk/toolkit-ui/issues/109
The current method is restrictive and prevents content flow.

Refactor / Panel

---

CHANGELOG.md
components/_forms.scss

Provides error styling for checkbox and radio indicator borders
https://github.com/sky-uk/toolkit-ui/issues/33
Visually in all browsers

Checkbox / Radio Styling 

---

components/_shine.scss

New shine uses `background` not `background-image` which leads to position being overwritten
N/A
Breaks the positioning of the shine.
Visually checked in all browsers

Fix shine background position

---

CHANGELOG.md
components/_forms.scss

By default checkboxes/radio buttons should be stacked, but we should also provide inline styles for shorter captions.
https://github.com/sky-uk/toolkit-ui/issues/179
cc @StefanMcCready @liamhutchinson

[Feature] Inline Checkbox/Radio inputs

---

CHANGELOG.md
components/_shine.scss
package.json

`1.0.1` missed a crucial change to background-size - leading to awkward sizing on some smaller tiles on Sky Pages.
e.g.

[Patch] Shine sizing

---

CHANGELOG.md
components/_tile.scss
package.json

Refactored to use panel-indicator mixin. See https://github.com/sky-uk/toolkit-core/pull/150
https://github.com/sky-uk/toolkit-ui/issues/114
https://github.com/sky-uk/toolkit-core/pull/150
This allows people to easily use panel indicator on non-tile elements.
Tested locally

Updated tile to use new panel indicator mixin

---

CHANGELOG.md
components/_tile-fluid.scss
package.json

`$tile-fluid-base-breakpoint` is currently hardcoded meaning we can't specify a different value which is essential to integrate with Sky Pages.
n/a
* Fixes an integration issue with Sky Pages
* Allows customisation of base breakpoint values
Tested locally
n/a

Assign $tile-fluid-base-breakpoint as !default

---

.stylelintrc
CHANGELOG.md
components/_calendar.scss
components/_panel.scss
package.json

Utilises an updated CSS lint ruleset, taken from Sky's CSS Style Guide
**Not to be merged until [sky-uk/css](https://github.com/sky-uk/css) is production ready**
https://github.com/sky-uk/toolkit-core/issues/159
Improvements to existing lint, shareability in projects that don't consume the Toolkit for company-wide consistency.
TBC
N/A

[Linter] Update rules and move to sky-uk/css

---

.gitignore
CHANGELOG.md
components/_dropdown.scss

Provide a general summary of your changes in the Title above
I added a property to allow the button to be full-width when the button's parent have the className `c-dropdown--full` or `c-dropdown--full@small-only`
Please link to the issue here
This change was required because the className `c-dropdown--full` didn't apply full-width
Now the dropdown is full width when use `c-dropdown--full` and `c-dropdown--full@small-only`
I created a local project to test if the class worked, I tested `c-dropdown--full` and `c-dropdown--full@small-only`
Include details of your testing environment, and the tests you ran to
see how your change affects other areas of the code, etc.

fix width of the dropdown with the className 'c-dropdown--full'

---

.github/ISSUE_TEMPLATE.md

Update the issue template to redirect developers to the main repo for future issues.
This update shouldn't require a version bump.

Redirect new toolkit-ui issues to the main Toolkit repo

---

CHANGELOG.md
components/_shine.scss
package.json

Quick **Patches O'Houlihan** for the Shine transition
- Move opacity animation to `c-shine-context`
https://github.com/sky-uk/toolkit-ui/pull/218
Currently blocking Hero shine animation
Tested in toolkit-react and Sky Pages
---
cc/ @coderas

[Shine] Transition patch

---

CHANGELOG.md
components/_tile.scss
package.json

To be fully tested after next toolkit-core release.
---
- Update Changelog format
- Update toolkit-core version
- Enforce cursor for `c-tile__link`
https://github.com/sky-uk/toolkit-core/pull/174
https://github.com/sky-uk/toolkit-core/pull/173
Utilises new toolkit-core
TBC
N/A

[refs #000182, #000183] Update toolkit-core

---

CHANGELOG.md
components/_tabs.scss
package.json

This is to fix a bug where hidden articles are clickable instead of the active article
Found in sky-uk/sky-pages#4077
Bug fix
Tested in linked PR

Added z-index properties to c-tabs__article classes

---

CHANGELOG.md
components/_dropdown.scss
package.json

This PR adds additional styles to the `.c-dropdown__link` class to override default button styling when using a `DropdownButton` within the `Dropdown` component in toolkit-react (https://github.com/sky-uk/toolkit-react/pull/163). 
Dropdown component with DropdownButton items
Closes https://github.com/sky-uk/thundertribe/issues/293

Dropdown component - Add styles to support button element

---

CHANGELOG.md
components/_accordion.scss
components/_buttons.scss
components/_dropdown.scss
components/_forms.scss
components/_panel.scss
components/_tile-fluid.scss
components/_tile.scss
components/_tooltip.scss
components/_typography.scss
package.json

- Clone
- Run `npm i`
- Run `npm run build` to see warnings
- Implement `disable-warning` parameter for components to be upgraded
- Leave one warning for both `c-text-body-small` and `c-text-lead-small`.
https://github.com/sky-uk/toolkit/issues/215
Toolkit 2.0 preparation
All tests pass, no change in outputted CSS
```
➜  toolkit-ui git:(deprecation-warnings) ✗ npm run build
> sky-toolkit-ui@1.15.0 build /Users/jbe42/www/toolkit-ui
> npm run clean && mkdir -p ./build && cat ./test/_build.scss | node_modules/.bin/node-sass --include-path node_modules/ --output-style compressed > build/toolkit.css
> sky-toolkit-ui@1.15.0 clean /Users/jbe42/www/toolkit-ui
> rm -rf build
WARNING: Deprecation [typography]: `text-lead-small`
Support for `text-lead-small` (and `.c-text-lead-small`) will be …
```

[refs #215] Deprecations for Toolkit 2.0

---

_all.scss
components/_tile.scss

- Fix Tile Shine positioning
- Move Typography to the bottom of our UI imports
https://github.com/sky-uk/toolkit/issues/228
Further 2.0 development
All tests pass
See current error - https://stage-watch-pr-4477.herokuapp.com/

Various UI Amends

---

CHANGELOG.md
components/_tile.scss
package.json

**Please note, tests will fail until https://github.com/sky-uk/toolkit-core/pull/190 is merged**
---
- Rename our mixins to prepare for 2.0 deprecation
https://github.com/sky-uk/toolkit/issues/223
Further 2.0 development
All tests pass

Deprecate Gradient Mixins
